ci:
  collect:
    # Serve the built public/ directory locally
    staticDistDir: ./public
    numberOfRuns: 1
    # Check the homepage — representative of all pages
    url:
      - "http://localhost/"

  assert:
    assertions:
      # Current scores: Performance 98, Accessibility 100, Best Practices 100, SEO 100
      # Thresholds set ~10-15 points below current to catch significant regressions
      "categories:performance":
        - error
        - minScore: 0.85
      "categories:accessibility":
        - error
        - minScore: 0.90
      "categories:best-practices":
        - error
        - minScore: 0.90
      "categories:seo":
        - error
        - minScore: 0.90
