baseurl = "https://kakkoyun.me"
title = "Kemal Akkoyun"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-135893796-2"
disqusShortname = "kakkoyun"

[params]
    author = "Kemal Akkoyun"
    info = "Average Infrastructure Engineer"
    description = "Kemal Akkoyun's personal website"
    keywords = "blog,developer,personal,software,engineer,monitoring,observability,infrastructure"
    avatarurl = "https://avatars1.githubusercontent.com/u/536449?v=4"

    favicon_32 = "/img/favicon-32x32.png" # TODO
    favicon_16 = "/img/favicon-16x16.png" # TODO

    footercontent = "Average Software Engineer. FOSS Enthusiast. Distributed systems. Reliability. Observability. Monitoring."

    hidecredits = true
    hidecopyright = false

    rtl = false
    math = true

    dateformat = "January 2, 2006"

    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/kakkoyun/me/tree/"

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # # Custom CSS
    # custom_css = []

    # # Custom JS
    # custom_js = []

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/kakkoyun/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/kkakkoyun/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://linkedin.com/in/kakkoyun/"
[[params.social]]
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 4
    url = "https://stackoverflow.com/u/1113525/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium fa-2x"
    weight = 5
    url = "https://medium.com/@kakkoyun/"
[[params.social]]
    name = "YouTube"
    icon = "fab fa-youtube fa-2x"
    weight = 6
    url = "https://www.youtube.com/playlist?list=PL3P7-fer_ILLtH_ZtQDQhDAEgTo5r9OnB"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 7
    url = "https://kakkoyun.me/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Talks"
    weight = 4
    url = "/talks/"
# [[menu.main]]
#     name = "CV"
#     weight = 5
#     url = "/cv/"
# [[menu.main]]
#     name = "Stats"
#     weight = 6
#     url = "/stats/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
